### ISSUE TITLE
Zimlet uses /owncloud by default ?

### ISSUE THREAD

**Issue by Yamakasi** [barrydegraaff/owncloud-zimlet#25]
Hi,

I did a new install of your zimlet and checked my apachelogs on the owncloud server and it seems that the zimlet uses, or tries, domain.tld/owncloud by default where my install is in domain.tld

Any clue here ?

Thanks Barry!

Matt

**Comment by barrydegraaff** [comment]
Yes, please read the readme, on how to configure that
________________________________

**Comment by Yamakasi** [comment]
Yes I did, but I do 

location /owncloud {
    proxy_pass https://myownclouddomain.tld;
}

which is not going to work.

location / {
    proxy_pass https://myownclouddomain.tld;
}

Als not as you have a duplicate / than.

**Comment by barrydegraaff** [comment]
Please install owncloud zimlet as if your owncloud was installed in the /owncloud location,

Then add this to your apache config on the ownCloud server:
https://github.com/barrydegraaff/owncloud-zimlet/blob/master/owncloud/owncloud-custom.conf
Please change the /var/www/html/owncloud/ to match your path. I will add to the wiki.

Your owncloud server should then be under
https://yourowncloud.com  and
https://yourowncloud.com/owncloud

And with the Zimbra proxy:
https://zimbraserver.com/owncloud

**Comment by barrydegraaff** [comment]
I have added this situation to the wiki:
https://github.com/barrydegraaff/owncloud-zimlet/wiki/ownCloud-in-a-different-location

**Comment by Yamakasi** [comment]
Sounds good indeed! I will test it today!

**Comment by Yamakasi** [comment]
Tis is not solved yet.

The alias works but owncloud seems to try to access owncloud @ mydomain.tld instead of owncloud.mydomain.tld

I might have mistyped that as I'm using a subdomain, but this should be possible too.

**Comment by barrydegraaff** [comment]
I tried it here and it works fine. Please show your config.
________________________________

**Comment by Yamakasi** [comment]
It's exactly the same as in the readme where my proxy is on
owncloud.domain.tld. It doesn' t even touch that server it goes directly to
domain.tld/owncloud/.....


2015-10-09 21:53 GMT+02:00 Barry de Graaff <notifications@github.com>:

**Comment by barrydegraaff** [comment]
Your proxy is on the owncloud server, then the config is a lot different.

I do not understand what you mean with owncloud @ mydomain.tld (what is that)

Anyways I understand that this is your oncloud installation url:
owncloud.domain.tld

You should first modify apache config to have also:
owncloud.domain.tld/owncloud

owncloud-custom.conf cannot make your request go to domain.tld/owncloud/

at least to my understanding, but obviously there is something in your apache config rewriting/redirecting that we are missing here. And I think it may be specific to your case.

Try and add : 
AllowOverride None 

In all your config files, also replace AllowOverride All with AllowOverride None in owncloud-custom.conf make sure to run apache configtest, restart apache and verify you have:
owncloud.domain.tld
owncloud.domain.tld/owncloud

Then we can go on to configuring ZImbra

**Comment by Yamakasi** [comment]
Hi Barry,

That is all set, my alias works as you say:

owncloud.domain.tld/owncloud

Since when is my proxy on the owncloud server ? it's not, it's only serving
an alias.



2015-10-09 22:52 GMT+02:00 Barry de Graaff <notifications@github.com>:

**Comment by barrydegraaff** [comment]
OK that sounds good, you should make sure the following config is present on your Zimbra server:

Make sure to have the correct protocol http/https:
[root@myzimbra ~]# nano /opt/zimbra/conf/nginx/templates/nginx.conf.web.https.default.template
location /owncloud/ {
    proxy_pass https://owncloud.domain.tld/owncloud/;
}
Then the config_template.xml  for the zimlet should stay as default, no changes needed:
<zimletConfig name="tk_barrydegraaff_owncloud_zimlet" version="1.0">
    <global>
        <property name="proxy_location">/owncloud</property>
        <property name="dav_path">/remote.php/webdav/</property>
        <property name="disable_link_sharing">false</property>
        <property name="disable_password_storing">false</property>
    </global>
</zimletConfig>


Reboot your ZImbra server, still no joy? What Zimbra version, ownCloud version, and Zimlet version you are using?

**Comment by yoppiesetiawan** [comment]
Hi Barry,

my server has configured from your README.md

owncloud server has setup done with conf owncloud-custom.conf

now can be access https://owncloud.example.com/owncloud

and Zimbra Server setup with proxy location
location /owncloud/ {
proxy_pass https://owncloud.example.com/owncloud/;
}

already try zmcontrol restart
but still The requested URL was not found on this server.
Please try again later.
ERROR: 404
« Go back

is it necessary to reboot the server ? because my zimbra has production server.. it will impact many users.

**Comment by barrydegraaff** [comment]
yep, that is cache for you, reboot will most likely help, you can also try:

  
  



zmcontrol fc allzmproxyctl restart
If you are sure your proxy on Zimbra actually proxies, and it still does notwork, reboot is the only way to go.

Barry

**Comment by barrydegraaff** [comment]
Don't forget to flush your browser cache or temporary files, while you're at it.

**Comment by yoppiesetiawan** [comment]
i already run zmcontrol fc all & zmproxyctl restart still not work.
Clear Cache on browser, and try another browser doesnt work too.. hahaha
Okay.. i`ll try reboot after office hour.

i`ll report after reboot server.

**Comment by yoppiesetiawan** [comment]
Hi Barry,


I`ve reboot the server..
but still not work :(
Same ERROR Codes

https://mail.example.com:443/owncloud/remote.php/webdav/ RESPONSE 501 null
"GET /owncloud/ocs/zcs.php?path=havesession HTTP/1.1" 404

it means my Zimbra server cant link to https://owncloud.example.com/owncloud/

here the screenshoot :

![screenshot_1](https://cloud.githubusercontent.com/assets/15098893/10453138/2fea9f1e-71d4-11e5-8ef5-c508f8e66cfc.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/15098893/10453139/2fec25c8-71d4-11e5-9b23-6a15d1e7cb47.png)

**Comment by barrydegraaff** [comment]
Does this work:

Please do NOT specify 443 in your config:
https://mail.example.com/owncloud/

**Comment by barrydegraaff** [comment]
Output of zmcontrol -v please and also show the proxy config of:
 /opt/zimbra/conf/nginx/templates/nginx.conf.web.https.default.template

and also show:
 /opt/zimbra/zimlets-deployed/_dev/tk_barrydegraaff_owncloud_zimlet/config_template.xml

**Comment by barrydegraaff** [comment]
And the output of netstat -tulpn you may mail this if you don't like to pass it in public

Maybe your proxy is not in front of Zimbra

**Comment by barrydegraaff** [comment]
[root@beta ~]# netstat -tulpn | grep 443
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      19096/nginx: master 
tcp        0      0 0.0.0.0:8443            0.0.0.0:*               LISTEN      18843/java  

Is good

**Comment by yoppiesetiawan** [comment]
Hi Barry, sorry to reply now.. because yesterday my office has off ( Islamic new year )

1. i do not add 443 to any config, its a default zimbra.log. maybe log cant parsing https port.. so he wrote port too ( 443 ).

2. Zmcontrol -v =
Release 8.6.0.GA.1153.UBUNTU12.64 UBUNTU12_64 FOSS edition.

3. netstat -tunlp | grep 443
root@mail:~# netstat -tulpn | grep 443
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      3955/java

there is no nginx listen on that SSL port.

when i netstat -tunlp | grep nginx
root@mail:~# netstat -tulpn | grep nginx
tcp        0      0 0.0.0.0:110             0.0.0.0:*               LISTEN      17177/nginx.conf
tcp        0      0 0.0.0.0:143             0.0.0.0:*               LISTEN      17177/nginx.conf
tcp        0      0 0.0.0.0:993             0.0.0.0:*               LISTEN      17177/nginx.conf
tcp        0      0 0.0.0.0:995             0.0.0.0:*               LISTEN      17177/nginx.conf

![screenshot_1](https://cloud.githubusercontent.com/assets/15098893/10503288/c8231bf8-731e-11e5-8439-8024e095e741.png)

**Comment by barrydegraaff** [comment]
That means your nginx is NOT proxying your Zimbra web interface, and that is why you see 404, as the /owncloud is not in jetty, your web server, please run at your own risk:

        zmproxyconfig -e -w -o -a 8080:80:8443:443 -x https -H `zmhostname` 

And then zmcontrol restart, that should enable proxy en then your /owncloud should work, please report back to me, if this did work or not, so I can add all this to the install guide.

Thanks Barry

**Comment by yoppiesetiawan** [comment]
Hi Barry,


sorry, i`ve realized in my ZimbraAdmin.. there is Proxy menu and from begining it was not enabled by default.

Here my Admin Menu :

![proxy-not enabled](https://cloud.githubusercontent.com/assets/15098893/10504973/ff666436-7331-11e5-9b4e-be3049b4a855.png)

**Comment by barrydegraaff** [comment]
I did not know there was a gui for that...

**Comment by barrydegraaff** [comment]
I have not tested that, or investigated, the CLI command should work...

**Comment by yoppiesetiawan** [comment]
Okay Barry,

I just found some url about this reverse proxy nginx in Zimbra.
https://wiki.zimbra.com/wiki/Enabling_Zimbra_Proxy

your CLI command same with that url.

i will try, but as ussualy... after office hour i can restart the server/service. hahaha

**Comment by barrydegraaff** [comment]
That is no problem, sysadmins should not be in a hurry to deploy new features.

  
  



I say 'at your own risk'- because things like zmproxyconfig and zmprov may breakthings, if not well tested or if there are bugs in ZImbra, or if your setup is differentthen expected.
My colleague tested this command twice, and I did ask the folks at Zimbra, they saythat this is the way to go... but in the end you are still responsible.
It does help with improving the install guides, so I am happy to provide this support.
Barry

**Comment by yoppiesetiawan** [comment]
Hi Barry,

i just did the command zmproxyconfig -e -w -o -a 8080:80:8443:443 -x https -H `zmhostname`

you must :

- su zimbra
- ./libexec/zmproxyconfig -e -w -o -a 8080:80:8443:443 -x https -H `zmhostname`
- zmcontrol restart


And now my Zimbra was work with Owncloud tab and save to owncloud.

![work1](https://cloud.githubusercontent.com/assets/15098893/10511360/e01873d6-7362-11e5-8a71-27d850489c65.png)
![work2](https://cloud.githubusercontent.com/assets/15098893/10511359/e01454f4-7362-11e5-84e3-0c704a0fb772.png)

**Comment by barrydegraaff** [comment]
Adding a wiki page on fixing Zimbra proxy
https://github.com/barrydegraaff/owncloud-zimlet/wiki/Install-and-enable-Zimbra-Proxy

**Comment by Yamakasi** [comment]
OK, I have time after tomorrow to pick this up also again :) Good work.

2015-10-15 14:35 GMT+02:00 Barry de Graaff <notifications@github.com>:

**Comment by pippo1993** [comment]
Hi, I installed your Zimlets on my server with already zimbra and apache2 configured to owncloud and more.

Both owncloud zimbra that run on http protocol .

zimbra on port 81 while owncloud on port 80 , both managed by apache as virtualserver .

I already have an zimbra proxy with the upgrade of zimbra package.

Oseguito all the driving but without success .

Thanks for your help

**Comment by barrydegraaff** [comment]
https://github.com/Zimbra-Community/owncloud-zimlet/wiki/ownCloud-in-a-different-location

**Comment by pippo1993** [comment]
The operation has already been performed but without success.

**Comment by barrydegraaff** [comment]
Please read the readme.md file : 
https://github.com/Zimbra-Community/owncloud-zimlet/blob/master/README.md

Also check out the wiki:
https://github.com/Zimbra-Community/owncloud-zimlet/wiki

Take your time for it, if you still have issues, make a new bugreport, that includes ALL the configuration you did. I am locking this issue, as it is hijacked multiple times now, and it almost always are how-to questions rather than actual bugs.
